name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Отримати код
        uses: actions/checkout@v3

      - name: Показати файли репозиторію
        run: ls -la

      - name: Перевірити bash скрипт
        run: bash monitoring.sh
